services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'mysql'
      MYSQL_ROOT_PASSWORD: '12345678'
    ports:
      - "3306:3306"
    volumes:
      - ./init-script.sql:/docker-entrypoint-initdb.d/init-script.sql
    networks:
      - microsvc

  kafka:
    build:
      context: "./kafka"
    ports:
      - "9092:9092"
    networks:
      - microsvc
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CREATE_TOPICS: "order.created:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - microsvc

  redis:
    ports:
      - '6379:6379'
    image: redis

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "14268:14268"
      - "16686:16686"
    networks:
      - microsvc

  productsvc:
    build:
      context: "./productsvc"
    ports:
      - "8080:8080"
    entrypoint: "/app/app ."
    restart: always
    environment:
      - APP_NAME=productsvc
      - DB_HOST=mysql
      - JAEGER_HOST=http://jaeger:14268/api/traces
    depends_on:
      - mysql
      - jaeger
      - redis
    networks:
      - microsvc

  ordersvc:
    build:
      context: "./ordersvc"
    ports:
      - "3000:3000"
    entrypoint: "/app/app serve"
    restart: always
    environment:
      - APP_NAME=stocksvc
      - DB_HOST=mysql
      - JAEGER_HOST=http://jaeger:14268/api/traces
      - KAFKA_HOST=kafka
    depends_on:
      - mysql
      - kafka
      - jaeger
    networks:
      - microsvc

  ordersvc-listener:
    build:
      context: "./ordersvc"
    entrypoint: "/app/app listen"
    restart: always
    environment:
      - APP_NAME=ordersvc-listener
      - DB_HOST=mysql
      - JAEGER_HOST=http://jaeger:14268/api/traces
      - KAFKA_HOST=kafka
    depends_on:
      - mysql
      - kafka
      - jaeger
    networks:
      - microsvc

  stocksvc:
    build:
      context: "./stocksvc"
    entrypoint: "/app/app ."
    restart: always
    environment:
      - APP_NAME=stocksvc
      - DB_HOST=mysql
      - JAEGER_HOST=http://jaeger:14268/api/traces
    depends_on:
      - mysql
      - jaeger
      - redis
    networks:
      - microsvc

  stocksvc-listener:
    build:
      context: "./stocksvc"
    entrypoint: "/app/app listen"
    restart: always
    environment:
      - APP_NAME=stocksvc-listener
      - DB_HOST=mysql
      - JAEGER_HOST=http://jaeger:14268/api/traces
      - KAFKA_HOST=kafka
    depends_on:
      - mysql
      - kafka
      - jaeger
      - ordersvc-listener
    networks:
      - microsvc

networks:
  microsvc:
    external: true