services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'mysql'
      MYSQL_ROOT_PASSWORD: '12345678'
    ports:
      - "3306:3306"
    volumes:
      - ./init-script.sql:/docker-entrypoint-initdb.d/init-script.sql
    networks:
      - microsvc

  redis:
    ports:
      - '6379:6379'
    image: redis

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "14268:14268"
      - "16686:16686"
    networks:
      - microsvc

  productsvc:
    build:
      context: "./productsvc"
    ports:
      - "8080:8080"
    networks:
      - microsvc

  ordersvc:
    build:
      context: "./ordersvc"
    ports:
      - "3000:3000"
    entrypoint: "/app/app serve"
    environment:
      - DB_HOST=mysql
    networks:
      - microsvc

  ordersvc-listener:
    build:
      context: "./ordersvc"
    entrypoint: "/app/app listen"
    environment:
      - DB_HOST=mysql
    networks:
      - microsvc

networks:
  microsvc: