// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	stock "gitlab.com/jeremylo/microsvc/grpc/model/stock"
)

// StockServiceClientMock is an autogenerated mock type for the StockServiceClientMock type
type StockServiceClientMock struct {
	mock.Mock
}

// FindEmptyStock provides a mock function with given fields: ctx, in, opts
func (_m *StockServiceClientMock) FindEmptyStock(ctx context.Context, in *stock.Message, opts ...grpc.CallOption) (*stock.Message, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *stock.Message
	if rf, ok := ret.Get(0).(func(context.Context, *stock.Message, ...grpc.CallOption) *stock.Message); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*stock.Message)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *stock.Message, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindStockByProduct provides a mock function with given fields: ctx, in, opts
func (_m *StockServiceClientMock) FindStockByProduct(ctx context.Context, in *stock.Message, opts ...grpc.CallOption) (*stock.Message, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *stock.Message
	if rf, ok := ret.Get(0).(func(context.Context, *stock.Message, ...grpc.CallOption) *stock.Message); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*stock.Message)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *stock.Message, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
