// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "gitlab.com/jeremylo/microsvc/productsvc/domain/model"
)

// ProductRepository is an autogenerated mock type for the ProductRepository type
type ProductRepository struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx
func (_m *ProductRepository) Get(ctx context.Context) []*model.Product {
	ret := _m.Called(ctx)

	var r0 []*model.Product
	if rf, ok := ret.Get(0).(func(context.Context) []*model.Product); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Product)
		}
	}

	return r0
}

// Show provides a mock function with given fields: ctx, id
func (_m *ProductRepository) Show(ctx context.Context, id *int) *model.Product {
	ret := _m.Called(ctx, id)

	var r0 *model.Product
	if rf, ok := ret.Get(0).(func(context.Context, *int) *model.Product); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Product)
		}
	}

	return r0
}
