// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Product struct {
	ID          *string  `json:"id"`
	Name        *string  `json:"name"`
	Price       *float64 `json:"price"`
	Description *string  `json:"description"`
	Rating      *float64 `json:"rating"`
	Category    *string  `json:"category"`
	Brand       *string  `json:"brand"`
	Thumbnail   *string  `json:"thumbnail"`
}
